name: Build and Release Ultracopier

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04  # Ubuntu noble

    steps:
    - name: Instalar herramientas necesarias
      run: |
        sudo apt update
        sudo apt install -y software-properties-common

    - name: Habilitar repositorio 'universe'
      run: |
        sudo add-apt-repository universe
        sudo apt update

    - name: Instalar dependencias Qt y build tools
      run: |
        sudo apt install -y make gcc build-essential libssl-dev \
        qtbase5-dev qt5-qmake qtbase5-dev-tools qttools5-dev-tools

    - name: Clonar el repositorio Ultracopier
      run: |
        git clone https://github.com/alphaonex86/Ultracopier
        cd Ultracopier

    - name: Extraer versión desde Version.h
      id: get_version
      run: |
        cd Ultracopier
        version=$(grep '#define ULTRACOPIER_VERSION' Version.h | cut -d'"' -f2)
        echo "version=$version" >> $GITHUB_OUTPUT

    - name: Compilar Ultracopier
      run: |
        cd Ultracopier
        find ./ -name '*.ts' -exec lrelease {} \; || true
        qmake ultracopier.pro
        make -j$(nproc)

    - name: Crear release y subir binario
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v${{ steps.get_version.outputs.version }}
        name: Ultracopier v${{ steps.get_version.outputs.version }}
        files: Ultracopier/ultracopier
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
